### ISSUE TITLE
New robot user agent to add to exclusions

### ISSUE THREAD

**Issue by PaulNeedham** [atmire/COUNTER-Robots#1]
User agent string: Docoloc

Docoloc bot is a web scraping bot used by the Docoloc plagiarism detection service. Docoloc bot searches papers for text fragments that also occur in other documents by using web scraping. Docoloc bot respects robots.txt.

(Ref: https://www.distilnetworks.com/bot-directory/bot/docoloc/)

**Comment by tomdesair** [comment]
PR https://github.com/atmire/COUNTER-Robots/pull/11 was merged which resolves this issue.
