### ISSUE TITLE
Escaped characters that don't need to be escaped

### ISSUE THREAD

**Issue by trianglePB** [atmire/COUNTER-Robots#18]
The following expression creates an error in the .NET programming language:
`lycos[\_\+]`

The character "\_" (char code 95) does not need escaping because it does not have a special meaning in Regular Expressions. Escaping character "\_" creates an error in .NET at runtime.
The character "+" (char code 43) is a special character in Regular Expressions, but within a character set it is not required to escape characters other than "\\", "-" and "]".

`lycos[\_\+]` should be changed to `lycos[_+]`

**Comment by bram-atmire** [comment]
thanks, merged !
