### ISSUE TITLE
New robot user agent strings to add to exclusions

### ISSUE THREAD

**Issue by PaulNeedham** [atmire/COUNTER-Robots#2]
API+scraper
G-i-g-a-b-o-t
Grammarly/1.0 (http://www.grammarly.com) _or_  Grammarly/1.0+(http://www.grammarly.com)
Riddler+(http://riddler.io/about)
EasyBib+AutoCite+(http://autocite-info.citation-api.com/)

**Comment by tomdesair** [comment]
Should we translate these to the following regexes? Note that a regex only has to match a part of the user agent.

- `API\+scraper` or `API[\+\s]scraper` ?
- `G-i-g-a-b-o-t` or just `b-o-t` ?
- `Grammarly/1.0\+?` or just `Grammarly` ?
- `Riddler\+` or `Riddler` ?
- `EasyBib\+AutoCite\+` or `EasyBib` ?

**Comment by PaulNeedham** [comment]
I’ll come back to you with the regexes required once these potential changes have been discussed by the Robots Working Group.

Thanks
Paul

**Comment by PaulNeedham** [comment]
Hi Tom

Sorry it’s taken so long to get back to you, it took a while to get feedback from the Robot Working Group. Please do update the COUNTER exclusion list with the following UAs/regexes:

User Agent String

Regex

Notes

Docoloc

Docoloc

Docoloc bot is a web scraping bot used by the Docoloc plagiarism detection service. Docoloc bot searches papers for text fragments that also occur in other documents by using web scraping. Docoloc bot respects robots.txt.
(Ref: https://www.distilnetworks.com/bot-directory/bot/docoloc/)

API+scraper

API[\+\s]scraper

Self-explanatory!

G-i-g-a-b-o-t

G-i-g-a-b-o-t

Self-explanatory!

Grammarly/1.0 (http://www.grammarly.com)

Grammarly

Grammarly/1.0 bot is a web scraping bot used by the writing tool Grammarly. Grammarly allows users to upload written pieces of work and then scrapes the content looking for grammar mistakes. Grammarly makes sure that everything users type is easy to read, effective, and mistake-free.
(Ref: https://www.distilnetworks.com/bot-directory/bot/grammarly1-0/)

Riddler+(http://riddler.io/about)

Riddler

Riddler is an online research project which investigates algorithms for mapping the topology of the Internet. Riddler bot scrapes data about public systems to use in its projects.
(Ref: https://www.distilnetworks.com/bot-directory/bot/riddler/)

EasyBib+AutoCite+(http://autocite-info.citation-api.com/)

EasyBib[\+\s]AutoCite[\+\s]

Easybib Autocite bot is a web scraping bot that allows users to type in a URL and Easybib bot will automatically scrape the necessary information to properly cite the web page, creating a bibliography. Easybib Autocite bot is not known to cause harm and helps give credit to original content owners.
(Ref: https://www.distilnetworks.com/bot-directory/bot/easybib-autocite/)


Thanks
Paul

--------------------------------------------------------------------------------------------------------
Paul A S Needham
Research & Innovation Manager
Kings Norton Library, Cranfield University, Cranfield, Bedfordshire MK43 0AL
orcid.org/0000-0001-9771-3469<http://orcid.org/0000-0001-9771-3469>

This email and any attachments to it may be confidential and are intended only for the named addressee. If you are not the named addressee, please accept our apology, notify the sender immediately and then delete the email. We request that you do not disclose, use, copy or distribute any information within it.

Any opinions expressed are not necessarily the corporate view of Cranfield University. This email is not intended to be contractually binding unless specifically stated and the sender is an authorised University signatory.

Whilst we have taken steps to ensure that this email and all attachments are free from any virus, we advise that, in keeping with good computing practice, the recipient should ensure they are actually virus free.

**Comment by tomdesair** [comment]
PR https://github.com/atmire/COUNTER-Robots/pull/11 was merged which resolves this issue.
