### ISSUE TITLE
Redundant pattern "voyager"

### ISSUE THREAD

**Issue by scheb** [atmire/COUNTER-Robots#24]
These two patterns do almost the same. The first one is a bit more restrictive, but the second one completely cover the first. So I'd suggest for the matter of simplicity, remove the first, keep the second.

```
  {
    "pattern": "^voyager\\/",
    "last_changed": "2017-08-08"
  },

  {
    "pattern": "voyager\\/",
    "last_changed": "2017-08-08"
  },
```

**Comment by PhilipVis** [comment]
Thanks @scheb for this suggestion! The redundant "voyager" pattern has now been removed.
