### ISSUE TITLE
Document expectations for "generated" folder

### ISSUE THREAD

**Issue by ctgraham** [atmire/COUNTER-Robots#3]
Currently, there is a ["generated" folder with a text list](https://github.com/atmire/COUNTER-Robots/blob/50f162b39f205fc20f153d4d19b8c33bfed25bfa/generated/COUNTER_Robots_list.txt), processed as [documented in the readme](https://github.com/atmire/COUNTER-Robots/tree/fb4dc61401c6787dfd9806b2dd6d622a2ff0f1bf#format-of-the-list).

An important use of this repository will be as a git submodule within other repositories.  When another project references this one, can it be assumed that the "generated" folder will be populated with a fresh version of the text-only patterns?  Or is the project which references this one responsible for regenerating this from the JSON?

For example, when a new robot is identified and incorporated by a pull request, will `generated/COUNTER_Robots_list.txt` reflect the change immediately, or will there be a formal release where the change is reflected, or is the text derivative not to be considered authoritative?

**Comment by bram-atmire** [comment]
Thanks @ctgraham, great comment and suggestion.

I confirm that we ARE automatically updating/keeping the generated file in sync, together with the JSON source and have just modified readme.md to clarify this. Closing this out.
