### ISSUE TITLE
Add Jersey to bot list

### ISSUE THREAD

**Issue by alanorth** [atmire/COUNTER-Robots#30]
I have 10,000 hits from this user agent in my logs:

```
Jersey/2.6 (HttpUrlConnection 1.8.0_152)
```

As far as I know this is the [Jersey REST framework](https://eclipse-ee4j.github.io/jersey/), which is not a human user.

**Comment by davidatmire** [comment]
Pattern added, see https://github.com/atmire/COUNTER-Robots/commit/0a2f0d8e71d0ba8dd5177d72c760410398701a92#diff-c3823ac6b39e6fca5b457bc604c3e149

Thanks for proposing this addition.
