### ISSUE TITLE
Add ReactorNetty to list

### ISSUE THREAD

**Issue by alanorth** [atmire/COUNTER-Robots#31]
I have several thousand hits from this user agent in my logs:

```
ReactorNetty/0.9.3.RELEASE
```

Seems to be [the reactor client/server framework for JVM](https://github.com/reactor/reactor-netty).

**Comment by davidatmire** [comment]
Pattern added, see https://github.com/atmire/COUNTER-Robots/commit/0a2f0d8e71d0ba8dd5177d72c760410398701a92#diff-c3823ac6b39e6fca5b457bc604c3e149

Thanks for proposing this addition.
