### ISSUE TITLE
Differences in Date format for last_changed

### ISSUE THREAD

**Issue by mkjp2011** [atmire/COUNTER-Robots#40]
Seeing that most dates are in format: yyyy-MM-dd

However, seeing some entries with format: yyyy-dd-MM

Shouldn't all dates be in the same format?

**Comment by davidatmire** [comment]
Hi,

Dates in the COUNTER_Robots_list.json file are mostly present for information purposes.
They are not used in the COUNTER_Robots_list.txt file.

This said, I'm happy to update the date format if there are inconsistencies.
After going very quickly through the json file, I only found one : 
https://github.com/atmire/COUNTER-Robots/blob/master/COUNTER_Robots_list.json#L1012

Did you find other occurrences ?

With thanks

**Comment by mkjp2011** [comment]
@davidatmire - thank you very much for the reply back! Yes, I honestly only found the one.

**Comment by davidatmire** [comment]
@mkjp2011 - thank you for checking too !
It's updated now : https://github.com/atmire/COUNTER-Robots/commit/64789469e46e5b0c3de97bae0bf1b563cf193ddd
